### ISSUE TITLE
Lines too long: need "make check"

### ISSUE THREAD

**Issue by johnousterhout** [PlatformLab/Arachne#4]
There are several places in Arachne and related packages where lines are longer than 80 characters. How about creating a "make check" target like the one in RAMCloud? Perhaps this should be set up to run automatically on commits, just like in RAMCloud?

**Comment by hq6** [comment]
Arachne, CoreArbiter, and PerfUtils have been updated. Each now has a make check option, although none yet has pre-commit hooks.

**Comment by hq6** [comment]
I have added a pre-commit hook for this to the three repositories.
